{"text": "Question:\nWhen running\npipenv run waitress-serve --listen=localhost:9696 q4-predict:app\nI get the following:\nThere was an exception (ValueError) importing your module.\nIt had these arguments:\n1. Malformed application 'q4-predict:app'\nAnswer:\nWaitress doesn\u2019t accept a dash in the python file name.\nThe solution is to rename the file replacing a dash with something else for instance with an underscore eg q4_predict.py\nAdded by Alex Litvinov", "section": "5. Deploying Machine Learning Models", "question": "waitress-serve shows Malformed application", "course": "machine-learning-zoomcamp", "document_id": "c13d811f"}