{"text": "When the request is processed in lambda function, mlflow library raises:\n2022/09/19 21:18:47 WARNING mlflow.pyfunc: Encountered an unexpected error (AttributeError(\"module 'dataclasses' has no attribute '__version__'\")) while detecting model dependency mismatches. Set logging level to DEBUG to see the full traceback.\nSolution: Increase the memory of the lambda function.\nAdded by MarcosMJD", "section": "Module 4: Deployment", "question": "Error raised when executing mlflow\u2019s pyfunc.load_model in lambda function.", "course": "mlops-zoomcamp", "document_id": "1667e95d"}