{"text": "Got the same warning message as Warrie Warrie when using \u201cmlflow.xgboost.autolog()\u201d\nIt turned out that this was just a warning message and upon checking MLflow UI (making sure that no \u201ctag\u201d filters were included), the model was actually automatically tracked in the MLflow.\nAdded by Bengsoon Chuah, Asked by Warrie Warrie, Answered by Anna Vasylytsya & Ivan Starovit", "section": "Module 2: Experiment tracking", "question": "MLflow.xgboost Autolog Model Signature Failure", "course": "mlops-zoomcamp", "document_id": "fd2b9972"}