{"text": "~\\anaconda3\\lib\\site-packages\\psycopg2\\__init__.py in connect(dsn, connection_factory, cursor_factory, **kwargs)\n120\n121     dsn = _ext.make_dsn(dsn, **kwargs)\n--> 122     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n123     if cursor_factory is not None:\n124         conn.cursor_factory = cursor_factory\nOperationalError: (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  database \"ny_taxi\" does not exist\nMake sure postgres is running. You can check that by running `docker ps`\n\u2705Solution: If you have postgres software installed on your computer before now, build your instance on a different port like 8080 instead of 5432", "section": "Module 1: Docker and Terraform", "question": "Postgres - OperationalError: (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  dodatabase \"ny_taxi\" does not exist", "course": "data-engineering-zoomcamp", "document_id": "9211bbd6"}