{"text": "Occurred while running : spark.createDataFrame(df_pandas).show()\nThis error is usually due to the python version, since spark till date of 2 march 2023 doesn\u2019t support python 3.11, try creating a new env with python version 3.8 and then run this command.\nOn the virtual machine, you can create a conda environment (here called myenv) with python 3.10 installed:\nconda create -n myenv python=3.10 anaconda\nThen you must run conda activate myenv to run python 3.10. Otherwise you\u2019ll still be running version 3.11. You can deactivate by typing conda deactivate.", "section": "Module 5: pyspark", "question": "PicklingError: Could not serialise object: IndexError: tuple index out of range.", "course": "data-engineering-zoomcamp", "document_id": "13dad632"}